# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasite', '0007_player_combinedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seasonStats',
            field=models.CharField(default='1', max_length=4096),
            preserve_default=False,
        ),
    ]
